#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/studentdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: liyi0123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
spring:
  http:
    multipart:
      enabled: true
server:
  port: 8081
